### ISSUE TITLE
Dashboard widgets doesn't count anything on site

### ISSUE THREAD

**Issue by h1sashin** [PiwikPRO/react-piwik-pro#10]
Hello, I'm new to PiwikPro and I'm trying to setup it in my NextJS app. So I started by following the docs and setup my `_app.tsx` component by adding
`
useEffect(() => {
		PiwikPro.initialize(
			process.env.NEXT_PUBLIC_STAGE === 'production'
				? 'prod_container_id'
				: 'dev_container_id',
			'container_url',
		);
	}, []);
`
and added a CustomEvent to my register form
`
CustomEvent.trackEvent('Forms', 'register', 'success');
`
_btw. I tried passing new user id as value but typescript screams that must be of type number, is it a bug or it must be a number?_

So I pushed it to my dev env and checked if there are piwin connecting errors, it's clear
Then entered Dashboard and created a widget to watch for that event I just created
![image](https://user-images.githubusercontent.com/25825628/185633144-60e0459a-e677-4864-b9a8-640fcdd82dd3.png)
It always dispaly 0 so I created a new widget that should count every /blog enterance following PiwikPro tutorial on youtube, it also doesn't count anything.
Then I entered Debug analytics in settings and there are all my events I made

So there is my question, am I doing something wrong?

Additionally PiwikPro found one enterance to my prod envitonment, but it's not even deployed yet and PiwikPro initialization is only on my dev branch.

**Comment by harmasz** [comment]
@h1sashin there's a short period before the events are displayed in reports and dashboards. It should take between 30 minutes and 1 hour to see them there, sometimes a bit more. If you see them in the Tracker debugger and they are not listed as "Broken events", then everything works correctly and you can check again a bit later.

**Comment by harmasz** [comment]
We're also currently working on a dedicated library for NextJS, because using the regular React one in NextJS apps can be tricky sometimes. It will be available here on GitHub and on NPM.

**Comment by h1sashin** [comment]
Okay, I was worried about my setup, but the data appeared for me after 2,5 hours, thanks for quick reply!
