### ISSUE TITLE
Add support for nextjs 15

### ISSUE THREAD

**Issue by wesolypl** [PiwikPRO/react-piwik-pro#42]
Hi, please add support for new nextjs release
Now we see an error
Could not resolve dependency:
npm ERR! peer next@">=13.0.0 <15.0.0" from @piwikpro/next-piwik-pro@2.1.1

**Comment by auto200** [comment]
Hello @wesolypl can You run `npm i @piwikpro/next-piwik-pro --force` and report any issues that You encounter? This would speed up the process :)

**Comment by auto200** [comment]
[@piwikpro/next-piwik-pro@3.1.2](https://github.com/PiwikPRO/next-piwik-pro/releases/tag/3.1.2) has been released. If You encounter any problems regarding nextjs 15, please submit an issue in [next-piwik-pro](https://github.com/PiwikPRO/next-piwik-pro/issues) repository
